//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from d:/UNIV/ANUL_II/LFC - Limbaje Formale si Compilatoare/Custom-Compiler/CustomCompiler/CustomCompiler/CustomLanguage.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="CustomLanguageParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface ICustomLanguageVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLanguageParser.base_structure"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBase_structure([NotNull] CustomLanguageParser.Base_structureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLanguageParser.global"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGlobal([NotNull] CustomLanguageParser.GlobalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLanguageParser.global_var"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGlobal_var([NotNull] CustomLanguageParser.Global_varContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLanguageParser.func_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunc_decl([NotNull] CustomLanguageParser.Func_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLanguageParser.body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBody([NotNull] CustomLanguageParser.BodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLanguageParser.openedblock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpenedblock([NotNull] CustomLanguageParser.OpenedblockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLanguageParser.closedblock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClosedblock([NotNull] CustomLanguageParser.ClosedblockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLanguageParser.if_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf_statement([NotNull] CustomLanguageParser.If_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLanguageParser.other_statements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOther_statements([NotNull] CustomLanguageParser.Other_statementsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLanguageParser.else_if_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElse_if_statement([NotNull] CustomLanguageParser.Else_if_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLanguageParser.else_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElse_statement([NotNull] CustomLanguageParser.Else_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLanguageParser.for_loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFor_loop([NotNull] CustomLanguageParser.For_loopContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLanguageParser.for_param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFor_param([NotNull] CustomLanguageParser.For_paramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLanguageParser.for_step"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFor_step([NotNull] CustomLanguageParser.For_stepContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLanguageParser.while_loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhile_loop([NotNull] CustomLanguageParser.While_loopContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLanguageParser.code_line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCode_line([NotNull] CustomLanguageParser.Code_lineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLanguageParser.return"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturn([NotNull] CustomLanguageParser.ReturnContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>aditionThenEqExp</c>
	/// labeled alternative in <see cref="CustomLanguageParser.attribution"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAditionThenEqExp([NotNull] CustomLanguageParser.AditionThenEqExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>subtractThenEqExp</c>
	/// labeled alternative in <see cref="CustomLanguageParser.attribution"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubtractThenEqExp([NotNull] CustomLanguageParser.SubtractThenEqExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>multiplyThenEqExp</c>
	/// labeled alternative in <see cref="CustomLanguageParser.attribution"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiplyThenEqExp([NotNull] CustomLanguageParser.MultiplyThenEqExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>divideThenEqExp</c>
	/// labeled alternative in <see cref="CustomLanguageParser.attribution"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDivideThenEqExp([NotNull] CustomLanguageParser.DivideThenEqExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>moduloThenEqExp</c>
	/// labeled alternative in <see cref="CustomLanguageParser.attribution"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuloThenEqExp([NotNull] CustomLanguageParser.ModuloThenEqExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>equalExp</c>
	/// labeled alternative in <see cref="CustomLanguageParser.attribution"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEqualExp([NotNull] CustomLanguageParser.EqualExpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLanguageParser.param_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParam_decl([NotNull] CustomLanguageParser.Param_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLanguageParser.other_param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOther_param([NotNull] CustomLanguageParser.Other_paramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLanguageParser.init_param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInit_param([NotNull] CustomLanguageParser.Init_paramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLanguageParser.var_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVar_decl([NotNull] CustomLanguageParser.Var_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLanguageParser.other_var"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOther_var([NotNull] CustomLanguageParser.Other_varContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLanguageParser.init_var"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInit_var([NotNull] CustomLanguageParser.Init_varContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>smallerEqExp</c>
	/// labeled alternative in <see cref="CustomLanguageParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSmallerEqExp([NotNull] CustomLanguageParser.SmallerEqExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>preincrementExp</c>
	/// labeled alternative in <see cref="CustomLanguageParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPreincrementExp([NotNull] CustomLanguageParser.PreincrementExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>variableAtomExp</c>
	/// labeled alternative in <see cref="CustomLanguageParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableAtomExp([NotNull] CustomLanguageParser.VariableAtomExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>valueAtomEXp</c>
	/// labeled alternative in <see cref="CustomLanguageParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValueAtomEXp([NotNull] CustomLanguageParser.ValueAtomEXpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>predecrementExp</c>
	/// labeled alternative in <see cref="CustomLanguageParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPredecrementExp([NotNull] CustomLanguageParser.PredecrementExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>logicNotExp</c>
	/// labeled alternative in <see cref="CustomLanguageParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicNotExp([NotNull] CustomLanguageParser.LogicNotExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionCallExp</c>
	/// labeled alternative in <see cref="CustomLanguageParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionCallExp([NotNull] CustomLanguageParser.FunctionCallExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>postdecrementExp</c>
	/// labeled alternative in <see cref="CustomLanguageParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPostdecrementExp([NotNull] CustomLanguageParser.PostdecrementExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>moduloExp</c>
	/// labeled alternative in <see cref="CustomLanguageParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuloExp([NotNull] CustomLanguageParser.ModuloExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>greaterEqExp</c>
	/// labeled alternative in <see cref="CustomLanguageParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGreaterEqExp([NotNull] CustomLanguageParser.GreaterEqExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>smallerExp</c>
	/// labeled alternative in <see cref="CustomLanguageParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSmallerExp([NotNull] CustomLanguageParser.SmallerExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>greaterExp</c>
	/// labeled alternative in <see cref="CustomLanguageParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGreaterExp([NotNull] CustomLanguageParser.GreaterExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>logicAndExp</c>
	/// labeled alternative in <see cref="CustomLanguageParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicAndExp([NotNull] CustomLanguageParser.LogicAndExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>logicOrExp</c>
	/// labeled alternative in <see cref="CustomLanguageParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicOrExp([NotNull] CustomLanguageParser.LogicOrExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>paranhesisExp</c>
	/// labeled alternative in <see cref="CustomLanguageParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParanhesisExp([NotNull] CustomLanguageParser.ParanhesisExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>subtractExp</c>
	/// labeled alternative in <see cref="CustomLanguageParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubtractExp([NotNull] CustomLanguageParser.SubtractExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>sameValueExp</c>
	/// labeled alternative in <see cref="CustomLanguageParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSameValueExp([NotNull] CustomLanguageParser.SameValueExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>diffValueExp</c>
	/// labeled alternative in <see cref="CustomLanguageParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDiffValueExp([NotNull] CustomLanguageParser.DiffValueExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>multiplyExp</c>
	/// labeled alternative in <see cref="CustomLanguageParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiplyExp([NotNull] CustomLanguageParser.MultiplyExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>divideExp</c>
	/// labeled alternative in <see cref="CustomLanguageParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDivideExp([NotNull] CustomLanguageParser.DivideExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>aditionExp</c>
	/// labeled alternative in <see cref="CustomLanguageParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAditionExp([NotNull] CustomLanguageParser.AditionExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>postincrementExp</c>
	/// labeled alternative in <see cref="CustomLanguageParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPostincrementExp([NotNull] CustomLanguageParser.PostincrementExpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLanguageParser.instruction_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstruction_list([NotNull] CustomLanguageParser.Instruction_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLanguageParser.other_instructions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOther_instructions([NotNull] CustomLanguageParser.Other_instructionsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLanguageParser.return_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturn_type([NotNull] CustomLanguageParser.Return_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLanguageParser.data_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitData_type([NotNull] CustomLanguageParser.Data_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLanguageParser.data_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitData_value([NotNull] CustomLanguageParser.Data_valueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLanguageParser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitName([NotNull] CustomLanguageParser.NameContext context);
}
